driver:
  name: terraform
provisioner:
  name: terraform
  variable_files:
    - test/fixtures/terraform.tfvars
transport:
  name: ssh
verifier:
  name: terraform
  format: doc
  groups:
    - name: hosts
      attributes:
        public_ip: public_ip
      controls:
        - sshd
      hostnames: public_ip
      port: 22
      username: ec2-user
platforms:
  - name: amazon
suites:
  - name: default
